// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: golemporal/protobuf/metadata.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Metadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowId    string                 `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	RunId         string                 `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	WorkflowType  string                 `protobuf:"bytes,3,opt,name=workflow_type,json=workflowType,proto3" json:"workflow_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metadata) Reset() {
	*x = Metadata{}
	mi := &file_golemporal_protobuf_metadata_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metadata) ProtoMessage() {}

func (x *Metadata) ProtoReflect() protoreflect.Message {
	mi := &file_golemporal_protobuf_metadata_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metadata.ProtoReflect.Descriptor instead.
func (*Metadata) Descriptor() ([]byte, []int) {
	return file_golemporal_protobuf_metadata_proto_rawDescGZIP(), []int{0}
}

func (x *Metadata) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *Metadata) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *Metadata) GetWorkflowType() string {
	if x != nil {
		return x.WorkflowType
	}
	return ""
}

var File_golemporal_protobuf_metadata_proto protoreflect.FileDescriptor

const file_golemporal_protobuf_metadata_proto_rawDesc = "" +
	"\n" +
	"\"golemporal/protobuf/metadata.proto\x12\x13golemporal.protobuf\"g\n" +
	"\bMetadata\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\tR\n" +
	"workflowId\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\x12#\n" +
	"\rworkflow_type\x18\x03 \x01(\tR\fworkflowTypeB1Z/github.com/soyacen/golemporal/protobuf;protobufb\x06proto3"

var (
	file_golemporal_protobuf_metadata_proto_rawDescOnce sync.Once
	file_golemporal_protobuf_metadata_proto_rawDescData []byte
)

func file_golemporal_protobuf_metadata_proto_rawDescGZIP() []byte {
	file_golemporal_protobuf_metadata_proto_rawDescOnce.Do(func() {
		file_golemporal_protobuf_metadata_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_golemporal_protobuf_metadata_proto_rawDesc), len(file_golemporal_protobuf_metadata_proto_rawDesc)))
	})
	return file_golemporal_protobuf_metadata_proto_rawDescData
}

var file_golemporal_protobuf_metadata_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_golemporal_protobuf_metadata_proto_goTypes = []any{
	(*Metadata)(nil), // 0: golemporal.protobuf.Metadata
}
var file_golemporal_protobuf_metadata_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_golemporal_protobuf_metadata_proto_init() }
func file_golemporal_protobuf_metadata_proto_init() {
	if File_golemporal_protobuf_metadata_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_golemporal_protobuf_metadata_proto_rawDesc), len(file_golemporal_protobuf_metadata_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_golemporal_protobuf_metadata_proto_goTypes,
		DependencyIndexes: file_golemporal_protobuf_metadata_proto_depIdxs,
		MessageInfos:      file_golemporal_protobuf_metadata_proto_msgTypes,
	}.Build()
	File_golemporal_protobuf_metadata_proto = out.File
	file_golemporal_protobuf_metadata_proto_goTypes = nil
	file_golemporal_protobuf_metadata_proto_depIdxs = nil
}
