// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: api/example.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HelloRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloRequest) Reset() {
	*x = HelloRequest{}
	mi := &file_api_example_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRequest) ProtoMessage() {}

func (x *HelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_example_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRequest.ProtoReflect.Descriptor instead.
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return file_api_example_proto_rawDescGZIP(), []int{0}
}

func (x *HelloRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *HelloRequest) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type HelloResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Result        int32                  `protobuf:"varint,2,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HelloResponse) Reset() {
	*x = HelloResponse{}
	mi := &file_api_example_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HelloResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloResponse) ProtoMessage() {}

func (x *HelloResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_example_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloResponse.ProtoReflect.Descriptor instead.
func (*HelloResponse) Descriptor() ([]byte, []int) {
	return file_api_example_proto_rawDescGZIP(), []int{1}
}

func (x *HelloResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HelloResponse) GetResult() int32 {
	if x != nil {
		return x.Result
	}
	return 0
}

var File_api_example_proto protoreflect.FileDescriptor

const file_api_example_proto_rawDesc = "" +
	"\n" +
	"\x11api/example.proto\x12\x16golemporal.example.api\"8\n" +
	"\fHelloRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"A\n" +
	"\rHelloResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x16\n" +
	"\x06result\x18\x02 \x01(\x05R\x06result2g\n" +
	"\x0fGreeterWorkflow\x12T\n" +
	"\x05Hello\x12$.golemporal.example.api.HelloRequest\x1a%.golemporal.example.api.HelloResponse2j\n" +
	"\x0fGreeterActivity\x12W\n" +
	"\bSayHello\x12$.golemporal.example.api.HelloRequest\x1a%.golemporal.example.api.HelloResponseB/Z-github.com/soyacen/golemporal/example/api;apib\x06proto3"

var (
	file_api_example_proto_rawDescOnce sync.Once
	file_api_example_proto_rawDescData []byte
)

func file_api_example_proto_rawDescGZIP() []byte {
	file_api_example_proto_rawDescOnce.Do(func() {
		file_api_example_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_example_proto_rawDesc), len(file_api_example_proto_rawDesc)))
	})
	return file_api_example_proto_rawDescData
}

var file_api_example_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_example_proto_goTypes = []any{
	(*HelloRequest)(nil),  // 0: golemporal.example.api.HelloRequest
	(*HelloResponse)(nil), // 1: golemporal.example.api.HelloResponse
}
var file_api_example_proto_depIdxs = []int32{
	0, // 0: golemporal.example.api.GreeterWorkflow.Hello:input_type -> golemporal.example.api.HelloRequest
	0, // 1: golemporal.example.api.GreeterActivity.SayHello:input_type -> golemporal.example.api.HelloRequest
	1, // 2: golemporal.example.api.GreeterWorkflow.Hello:output_type -> golemporal.example.api.HelloResponse
	1, // 3: golemporal.example.api.GreeterActivity.SayHello:output_type -> golemporal.example.api.HelloResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_example_proto_init() }
func file_api_example_proto_init() {
	if File_api_example_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_example_proto_rawDesc), len(file_api_example_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_api_example_proto_goTypes,
		DependencyIndexes: file_api_example_proto_depIdxs,
		MessageInfos:      file_api_example_proto_msgTypes,
	}.Build()
	File_api_example_proto = out.File
	file_api_example_proto_goTypes = nil
	file_api_example_proto_depIdxs = nil
}
