// Code generated by protoc-gen-golemporal. DO NOT EDIT.

package api

import (
	context "context"
	protobuf "github.com/soyacen/golemporal/protobuf"
	starter "github.com/soyacen/golemporal/starter"
	activity "go.temporal.io/sdk/activity"
	client "go.temporal.io/sdk/client"
	worker "go.temporal.io/sdk/worker"
	workflow "go.temporal.io/sdk/workflow"
)

var (
	AddActivity_Add_ActitityType = "/golemporal.example.api.AddActivity/Add"
)

type AddActivityClient interface {
	Add(ctx workflow.Context, in *AddRequest) (*AddResponse, error)
}

func NewAddActivityClient() AddActivityClient {
	return &addActivityClient{}
}

type addActivityClient struct{}

func (c *addActivityClient) Add(ctx workflow.Context, in *AddRequest) (*AddResponse, error) {
	var out AddResponse
	err := workflow.ExecuteActivity(ctx, AddActivity_Add_ActitityType, in).Get(ctx, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

type AddActivityServer interface {
	Add(context.Context, *AddRequest) (*AddResponse, error)
}

var (
	MultiActivity_Multi_ActitityType = "/golemporal.example.api.MultiActivity/Multi"
)

type MultiActivityClient interface {
	Multi(ctx workflow.Context, in *MultiRequest) (*MultiResponse, error)
}

func NewMultiActivityClient() MultiActivityClient {
	return &multiActivityClient{}
}

type multiActivityClient struct{}

func (c *multiActivityClient) Multi(ctx workflow.Context, in *MultiRequest) (*MultiResponse, error) {
	var out MultiResponse
	err := workflow.ExecuteActivity(ctx, MultiActivity_Multi_ActitityType, in).Get(ctx, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

type MultiActivityServer interface {
	Multi(context.Context, *MultiRequest) (*MultiResponse, error)
}

var (
	HelloWorkflow_Hello_WorkflowType = "/golemporal.example.api.HelloWorkflow/Hello"
)

type HelloWorkflowClient interface {
	Hello(ctx context.Context, in *HelloRequest, opts ...starter.Option) (*protobuf.Metadata, error)
}

type helloWorkflowClient struct {
	c         client.Client
	taskQueue string
}

func NewHelloWorkflowClient(c client.Client, taskQueue string) HelloWorkflowClient {
	return &helloWorkflowClient{c: c, taskQueue: taskQueue}
}

func (c *helloWorkflowClient) Hello(ctx context.Context, in *HelloRequest, opts ...starter.Option) (*protobuf.Metadata, error) {
	options := starter.NewOptions(c.taskQueue, opts...)
	run, err := c.c.ExecuteWorkflow(ctx, options.StartWorkflowOptions, HelloWorkflow_Hello_WorkflowType, in)
	if err != nil {
		return nil, err
	}
	md := &protobuf.Metadata{}
	md.WorkflowId = run.GetID()
	md.RunId = run.GetRunID()
	md.WorkflowType = HelloWorkflow_Hello_WorkflowType
	if options.Result == nil {
		return md, nil
	}
	if err := run.Get(ctx, options.Result); err != nil {
		return nil, err
	}
	return md, nil
}

type HelloWorkflowServer interface {
	Hello(workflow.Context, *HelloRequest) (*HelloResponse, error)
}

var (
	GoodbyeWorkflow_Goodbye_WorkflowType = "/golemporal.example.api.GoodbyeWorkflow/Goodbye"
)

type GoodbyeWorkflowClient interface {
	Goodbye(ctx context.Context, in *GoodbyeRequest, opts ...starter.Option) (*protobuf.Metadata, error)
}

type goodbyeWorkflowClient struct {
	c         client.Client
	taskQueue string
}

func NewGoodbyeWorkflowClient(c client.Client, taskQueue string) GoodbyeWorkflowClient {
	return &goodbyeWorkflowClient{c: c, taskQueue: taskQueue}
}

func (c *goodbyeWorkflowClient) Goodbye(ctx context.Context, in *GoodbyeRequest, opts ...starter.Option) (*protobuf.Metadata, error) {
	options := starter.NewOptions(c.taskQueue, opts...)
	run, err := c.c.ExecuteWorkflow(ctx, options.StartWorkflowOptions, GoodbyeWorkflow_Goodbye_WorkflowType, in)
	if err != nil {
		return nil, err
	}
	md := &protobuf.Metadata{}
	md.WorkflowId = run.GetID()
	md.RunId = run.GetRunID()
	md.WorkflowType = GoodbyeWorkflow_Goodbye_WorkflowType
	if options.Result == nil {
		return md, nil
	}
	if err := run.Get(ctx, options.Result); err != nil {
		return nil, err
	}
	return md, nil
}

type GoodbyeWorkflowServer interface {
	Goodbye(workflow.Context, *GoodbyeRequest) (*GoodbyeResponse, error)
}

func RegisterAddActivity(
	wk worker.Worker,
	server AddActivityServer,
) {
	wk.RegisterActivityWithOptions(server.Add, activity.RegisterOptions{
		Name:                          AddActivity_Add_ActitityType,
		DisableAlreadyRegisteredCheck: true,
	})

}

func RegisterMultiActivity(
	wk worker.Worker,
	server MultiActivityServer,
) {
	wk.RegisterActivityWithOptions(server.Multi, activity.RegisterOptions{
		Name:                          MultiActivity_Multi_ActitityType,
		DisableAlreadyRegisteredCheck: true,
	})

}

func RegisterHelloWorkflow(
	wk worker.Worker,
	server HelloWorkflowServer,
) {
	wk.RegisterWorkflowWithOptions(server.Hello, workflow.RegisterOptions{
		Name:                          HelloWorkflow_Hello_WorkflowType,
		DisableAlreadyRegisteredCheck: true,
	})

}

func RegisterGoodbyeWorkflow(
	wk worker.Worker,
	server GoodbyeWorkflowServer,
) {
	wk.RegisterWorkflowWithOptions(server.Goodbye, workflow.RegisterOptions{
		Name:                          GoodbyeWorkflow_Goodbye_WorkflowType,
		DisableAlreadyRegisteredCheck: true,
	})

}
