// Code generated by protoc-gen-golemporal. DO NOT EDIT.

package api

import (
	context "context"
	starter "github.com/soyacen/golemporal/starter"
	activity "go.temporal.io/sdk/activity"
	client "go.temporal.io/sdk/client"
	worker "go.temporal.io/sdk/worker"
	workflow "go.temporal.io/sdk/workflow"
)

type AddActivityClient interface {
	Add(ctx workflow.Context, in *AddRequest) (*AddResponse, error)
}

func NewAddActivityClient() AddActivityClient {
	return &addActivityClient{}
}

type addActivityClient struct{}

func (c *addActivityClient) Add(ctx workflow.Context, in *AddRequest) (*AddResponse, error) {
	var out AddResponse
	err := workflow.ExecuteActivity(ctx, "/golemporal.example.api.AddActivity/Add", in).Get(ctx, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

type AddActivityServer interface {
	Add(context.Context, *AddRequest) (*AddResponse, error)
}

type MultiActivityClient interface {
	Multi(ctx workflow.Context, in *MultiRequest) (*MultiResponse, error)
}

func NewMultiActivityClient() MultiActivityClient {
	return &multiActivityClient{}
}

type multiActivityClient struct{}

func (c *multiActivityClient) Multi(ctx workflow.Context, in *MultiRequest) (*MultiResponse, error) {
	var out MultiResponse
	err := workflow.ExecuteActivity(ctx, "/golemporal.example.api.MultiActivity/Multi", in).Get(ctx, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

type MultiActivityServer interface {
	Multi(context.Context, *MultiRequest) (*MultiResponse, error)
}

type GreeterWorkflowClient interface {
	Hello(ctx context.Context, in *HelloRequest, opts ...starter.Option) error
	Goodbye(ctx context.Context, in *GoodbyeRequest, opts ...starter.Option) error
}

type greeterWorkflowClient struct {
	c         client.Client
	taskQueue string
}

func NewGreeterWorkflowClient(c client.Client, taskQueue string) GreeterWorkflowClient {
	return &greeterWorkflowClient{c: c, taskQueue: taskQueue}
}

func (c *greeterWorkflowClient) Hello(ctx context.Context, in *HelloRequest, opts ...starter.Option) error {
	options := starter.NewOptions(c.taskQueue, opts...)
	run, err := c.c.ExecuteWorkflow(ctx, options.StartWorkflowOptions, "/golemporal.example.api.GreeterWorkflow/Hello", in)
	if err != nil {
		return err
	}
	if options.WorkflowID != nil {
		workflowID := run.GetID()
		*options.WorkflowID = workflowID
	}
	if options.RunID != nil {
		runID := run.GetRunID()
		*options.RunID = runID
	}
	if options.Result != nil {
		if err := run.Get(ctx, options.Result); err != nil {
			return err
		}
	}
	return nil
}

func (c *greeterWorkflowClient) Goodbye(ctx context.Context, in *GoodbyeRequest, opts ...starter.Option) error {
	options := starter.NewOptions(c.taskQueue, opts...)
	run, err := c.c.ExecuteWorkflow(ctx, options.StartWorkflowOptions, "/golemporal.example.api.GreeterWorkflow/Goodbye", in)
	if err != nil {
		return err
	}
	if options.WorkflowID != nil {
		workflowID := run.GetID()
		*options.WorkflowID = workflowID
	}
	if options.RunID != nil {
		runID := run.GetRunID()
		*options.RunID = runID
	}
	if options.Result != nil {
		if err := run.Get(ctx, options.Result); err != nil {
			return err
		}
	}
	return nil
}

type GreeterWorkflowServer interface {
	Hello(workflow.Context, *HelloRequest) (*HelloResponse, error)
	Goodbye(workflow.Context, *GoodbyeRequest) (*GoodbyeResponse, error)
}

func RegisterGreeterWorkflowWorker(
	w worker.Worker,
	greeterWorkflowServer GreeterWorkflowServer,
	addActivityServer AddActivityServer,
	multiActivityServer MultiActivityServer,
) {
	w.RegisterActivityWithOptions(addActivityServer.Add, activity.RegisterOptions{
		Name:                          "/golemporal.example.api.AddActivity/Add",
		DisableAlreadyRegisteredCheck: true,
	})

	w.RegisterActivityWithOptions(multiActivityServer.Multi, activity.RegisterOptions{
		Name:                          "/golemporal.example.api.MultiActivity/Multi",
		DisableAlreadyRegisteredCheck: true,
	})

	w.RegisterWorkflowWithOptions(greeterWorkflowServer.Hello, workflow.RegisterOptions{
		Name:                          "/golemporal.example.api.GreeterWorkflow/Hello",
		DisableAlreadyRegisteredCheck: true,
	})

	w.RegisterWorkflowWithOptions(greeterWorkflowServer.Goodbye, workflow.RegisterOptions{
		Name:                          "/golemporal.example.api.GreeterWorkflow/Goodbye",
		DisableAlreadyRegisteredCheck: true,
	})

}
