// Code generated by protoc-gen-golemporal. DO NOT EDIT.
// versions:
// - protoc-gen-golemporal v1.6.0
// - protoc             v6.33.4
// source: example/example.proto

package example

import (
	context "context"

	"github.com/soyacen/golemporal/starter"
	"go.temporal.io/sdk/activity"
	"go.temporal.io/sdk/client"
	"go.temporal.io/sdk/worker"
	"go.temporal.io/sdk/workflow"
)

const (
	GreeterWorkflow_HelloWorkflow_FullMethodName = "/golemporal.example.GreeterWorkflow/HelloWorkflow"
)

type GreeterWorkflowClient interface {
	HelloWorkflow(ctx context.Context, in *HelloRequest, opts ...starter.Option) (*HelloResponse, error)
}

type greeterWorkflowClient struct {
	c         client.Client
	taskQueue string
}

func NewGreeterWorkflowClient(c client.Client, taskQueue string) GreeterWorkflowClient {
	return &greeterWorkflowClient{c: c, taskQueue: taskQueue}
}

func (c *greeterWorkflowClient) HelloWorkflow(ctx context.Context, in *HelloRequest, opts ...starter.Option) (*HelloResponse, error) {
	run, err := c.c.ExecuteWorkflow(ctx, starter.NewOptions(c.taskQueue, opts...), GreeterWorkflow_HelloWorkflow_FullMethodName, in)
	if err != nil {
		return nil, err
	}
	out := new(HelloResponse)
	if err := run.Get(ctx, out); err != nil {
		return nil, err
	}
	return out, nil
}

type GreeterWorkflowServer interface {
	HelloWorkflow(workflow.Context, *HelloRequest) (*HelloResponse, error)
}

func RegisterGreeterWorker(w worker.Worker, srv GreeterWorkflowServer) {
	w.RegisterWorkflowWithOptions(srv.HelloWorkflow, workflow.RegisterOptions{
		Name:                          GreeterWorkflow_HelloWorkflow_FullMethodName,
		DisableAlreadyRegisteredCheck: true,
	})
}

const (
	GreeterActivity_SayHello_FullMethodName = "/golemporal.example.GreeterActivity/SayHello"
)

type GreeterActivityClient interface {
	SayHello(ctx workflow.Context, in *HelloRequest) (*HelloResponse, error)
}

func NewGreeterActivityClient() GreeterActivityClient {
	return &greeterActivityClient{}
}

type greeterActivityClient struct{}

func (c *greeterActivityClient) SayHello(ctx workflow.Context, in *HelloRequest) (*HelloResponse, error) {
	var out HelloResponse
	err := workflow.ExecuteActivity(ctx, GreeterActivity_SayHello_FullMethodName, in).Get(ctx, &out)
	if err != nil {
		return nil, err
	}
	return &out, nil
}

type GreeterActivityServer interface {
	SayHello(context.Context, *HelloRequest) (*HelloResponse, error)
}

func RegisterGreeterActivity(w worker.Worker, srv GreeterActivityServer) {
	w.RegisterActivityWithOptions(srv.SayHello, activity.RegisterOptions{
		Name:                          GreeterActivity_SayHello_FullMethodName,
		DisableAlreadyRegisteredCheck: true,
	})
}
