package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/types/pluginpb"
)

var (
	contextPackage = protogen.GoImportPath("context")
	contextIdent   = contextPackage.Ident("Context")
)

var (
	workflowPackage      = protogen.GoImportPath("go.temporal.io/sdk/workflow")
	workflowContextIdent = workflowPackage.Ident("Context")
)

var (
	workerPackage      = protogen.GoImportPath("go.temporal.io/sdk/worker")
	workerContextIdent = workerPackage.Ident("Worker")
)

var (
	activityPackage              = protogen.GoImportPath("go.temporal.io/sdk/activity")
	activityRegisterOptionsIdent = activityPackage.Ident("RegisterOptions")
)

var (
	clientPackage     = protogen.GoImportPath("go.temporal.io/sdk/client")
	clientClientIdent = clientPackage.Ident("Client")
)

var (
	starterPackage         = protogen.GoImportPath("github.com/soyacen/golemporal/starter")
	starterOptionIdent     = starterPackage.Ident("Option")
	starterNewOptionsIdent = starterPackage.Ident("NewOptions")
)

var (
	protobufPackage = protogen.GoImportPath("github.com/soyacen/golemporal/protobuf")
	metadataIdent   = protobufPackage.Ident("Metadata")
)

var flags flag.FlagSet

var Version = "v0.2.3"

func main() {
	if len(os.Args) == 2 && os.Args[1] == "--version" {
		_, _ = fmt.Fprintf(os.Stdout, "%v %v\n", filepath.Base(os.Args[0]), Version)
		os.Exit(0)
	}
	options := &protogen.Options{ParamFunc: flags.Set}
	options.Run(func(plugin *protogen.Plugin) error {
		plugin.SupportedFeatures = uint64(pluginpb.CodeGeneratorResponse_FEATURE_PROTO3_OPTIONAL)
		for _, file := range plugin.Files {
			if !file.Generate {
				continue
			}
			if len(file.Services) <= 0 {
				continue
			}
			var count int
			for _, svc := range file.Services {
				serviceName := string(svc.Desc.Name())
				if strings.HasSuffix(serviceName, "Workflow") || strings.HasSuffix(serviceName, "Activity") {
					count++
				}
			}
			if count <= 0 {
				continue
			}
			generateFile(plugin, file)
		}
		return nil
	})
}

func generateFile(gen *protogen.Plugin, file *protogen.File) {
	filename := file.GeneratedFilenamePrefix + "_temporal.pb.go"
	g := gen.NewGeneratedFile(filename, file.GoImportPath)
	g.P("// Code generated by protoc-gen-golemporal. DO NOT EDIT.")
	g.P()
	g.P("package ", file.GoPackageName)
	g.P()

	var activities []*protogen.Service
	for _, svc := range file.Services {
		serviceName := string(svc.Desc.Name())
		if strings.HasSuffix(serviceName, "Activity") {
			generateActivityClient(g, svc)
			generateActivityServer(g, svc)
			activities = append(activities, svc)
		}
	}

	var workflows []*protogen.Service
	// only one workflow service is supported, so we can break after the first one
	for _, svc := range file.Services {
		serviceName := string(svc.Desc.Name())
		if strings.HasSuffix(serviceName, "Workflow") {
			generateWorkflowClient(g, svc)
			generateWorkflowServer(g, svc)
			workflows = append(workflows, svc)
		}
	}
	generateRegisterFunction(g, workflows, activities)
}

func generateActivityClient(g *protogen.GeneratedFile, svc *protogen.Service) {
	g.P("var (")
	for _, method := range svc.Methods {
		g.P(actitityTypeFullName(method), " = ", strconv.Quote(methodFullName(method)))
	}
	g.P(")")

	clientName := string(svc.Desc.Name()) + "Client"
	g.P("type ", clientName, " interface {")
	for _, method := range svc.Methods {
		inputType := method.Input.GoIdent
		outputType := method.Output.GoIdent
		g.P("", method.Desc.Name(), "(ctx ", workflowContextIdent, ", in *", inputType, ") (*", outputType, ", error)")
	}
	g.P("}")
	g.P()

	// Generate constructor
	g.P("func New", clientName, "() ", clientName, " {")
	g.P("return &", toLowerCase(clientName), "{}")
	g.P("}")
	g.P()

	// Generate private struct
	g.P("type ", toLowerCase(clientName), " struct {}")
	g.P()

	// Generate methods
	for _, method := range svc.Methods {
		inputType := method.Input.GoIdent
		outputType := method.Output.GoIdent
		methodName := string(method.Desc.Name())
		g.P("func (c *", toLowerCase(clientName), ") ", methodName, "(ctx ", workflowContextIdent, ", in *", inputType, ") (*", outputType, ", error) {")
		g.P("var out ", outputType)
		g.P("if err := workflow.ExecuteActivity(ctx, ", actitityTypeFullName(method), ", in).Get(ctx, &out); err != nil {")
		g.P("return nil, err")
		g.P("}")
		g.P("return &out, nil")
		g.P("}")
		g.P()
	}
}

func generateActivityServer(g *protogen.GeneratedFile, svc *protogen.Service) {
	serverName := string(svc.Desc.Name()) + "Server"
	// Generate interface
	g.P("type ", serverName, " interface {")
	for _, method := range svc.Methods {
		inputType := method.Input.GoIdent
		outputType := method.Output.GoIdent
		g.P("", method.Desc.Name(), "(", contextIdent, ", *", inputType, ") (*", outputType, ", error)")
	}
	g.P("}")
	g.P()
}

func generateWorkflowClient(g *protogen.GeneratedFile, svc *protogen.Service) {
	g.P("var (")
	for _, method := range svc.Methods {
		g.P(workflowTypeFullName(method), " = ", strconv.Quote(methodFullName(method)))
	}
	g.P(")")

	clientName := string(svc.Desc.Name()) + "Client"
	// Generate interface
	g.P("type ", clientName, " interface {")
	for _, method := range svc.Methods {
		inputType := method.Input.GoIdent
		g.P(method.Desc.Name(), "(ctx ", contextIdent, ", in *", inputType, ", opts ...", starterOptionIdent, ") (*", metadataIdent, ", error)")
	}
	g.P("}")
	g.P()

	// Generate private struct
	g.P("type ", toLowerCase(clientName), " struct {")
	g.P("c ", clientClientIdent)
	g.P("taskQueue string")
	g.P("}")
	g.P()

	// Generate constructor
	g.P("func New", clientName, "(c ", clientClientIdent, ", taskQueue string) ", clientName, " {")
	g.P("return &", toLowerCase(clientName), "{c: c, taskQueue: taskQueue}")
	g.P("}")
	g.P()

	// Generate methods
	for _, method := range svc.Methods {
		inputType := method.Input.GoIdent
		methodName := string(method.Desc.Name())
		g.P("func (c *", toLowerCase(clientName), ") ", methodName, "(ctx ", contextIdent, ", in *", inputType, ", opts ...", starterOptionIdent, ") (*", metadataIdent, ", error) {")
		g.P("options := ", starterNewOptionsIdent, "(c.taskQueue, opts...)")
		g.P("run, err := c.c.ExecuteWorkflow(ctx, options.StartWorkflowOptions, ", workflowTypeFullName(method), ", in)")
		g.P("if err != nil {")
		g.P("return nil, err")
		g.P("}")
		g.P("md := &", metadataIdent, "{")
		g.P("TaskQueue: c.taskQueue,")
		g.P("}")
		g.P("md.WorkflowId = run.GetID()")
		g.P("md.RunId = run.GetRunID()")
		g.P("md.WorkflowType = ", workflowTypeFullName(method))
		g.P("if options.Result == nil {")
		g.P("return md, nil")
		g.P("}")
		g.P("if err := run.Get(ctx, options.Result); err != nil {")
		g.P("return nil, err")
		g.P("}")
		g.P("return md, nil")
		g.P("}")
		g.P()
	}
}

func generateWorkflowServer(g *protogen.GeneratedFile, svc *protogen.Service) {
	serverName := string(svc.Desc.Name()) + "Server"
	g.P("type ", serverName, " interface {")
	for _, method := range svc.Methods {
		inputType := method.Input.GoIdent
		outputType := method.Output.GoIdent
		g.P("", method.Desc.Name(), "(", workflowContextIdent, ", *", inputType, ") (*", outputType, ", error)")
	}
	g.P("}")
	g.P()
}

func generateRegisterFunction(g *protogen.GeneratedFile, workflows []*protogen.Service, activities []*protogen.Service) {
	for _, activity := range activities {
		activityName := string(activity.Desc.Name()) + "Server"
		g.P("func Register", string(activity.Desc.Name()), "(")
		g.P("wk ", workerContextIdent, ",")
		g.P("server ", activityName, ",")
		g.P(") {")
		for _, method := range activity.Methods {
			g.P("wk.RegisterActivityWithOptions(server.", method.Desc.Name(), ", ", activityRegisterOptionsIdent, "{")
			g.P("Name: ", actitityTypeFullName(method), ",")
			g.P("DisableAlreadyRegisteredCheck: true,")
			g.P("})")
			g.P()
		}
		g.P("}")
		g.P()
	}

	for _, workflow := range workflows {
		workflowName := string(workflow.Desc.Name()) + "Server"
		g.P("func Register", string(workflow.Desc.Name()), "(")
		g.P("wk ", workerContextIdent, ",")
		g.P("server ", workflowName, ",")
		g.P(") {")
		for _, method := range workflow.Methods {
			g.P("wk.RegisterWorkflowWithOptions(server.", method.Desc.Name(), ", workflow.RegisterOptions{")
			g.P("Name: ", workflowTypeFullName(method), ",")
			g.P("DisableAlreadyRegisteredCheck: true,")
			g.P("})")
			g.P()
		}
		g.P("}")
		g.P()
	}
}

func toLowerCase(s string) string {
	if s == "" {
		return s
	}
	return strings.ToLower(s[:1]) + s[1:]
}

func workflowTypeFullName(method *protogen.Method) string {
	return fmt.Sprintf("%s_%s_WorkflowType", method.Parent.GoName, method.GoName)
}

func actitityTypeFullName(method *protogen.Method) string {
	return fmt.Sprintf("%s_%s_ActitityType", method.Parent.GoName, method.GoName)
}

func methodFullName(protoMethod *protogen.Method) string {
	return fmt.Sprintf("/%s/%s", protoMethod.Parent.Desc.FullName(), protoMethod.Desc.Name())
}
